addined ouput for error checking dynamo-DB (#78)

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -46,9 +46,13 @@ jobs:
        --source-bundle S3Bucket=elasticbeanstalk-us-west-1-431738351778,S3Key=ChatGDP-DiscordBot.zip
     - name: Deploy application version
       run: |
-       aws elasticbeanstalk update-environment \
-       --environment-name Chatgdpdiscordbot-env-1 \
-       --version-label "$(git rev-parse HEAD)"
+        result=$(aws elasticbeanstalk update-environment \
+        --environment-name Chatgdpdiscordbot-env-1 \
+        --version-label "$(git rev-parse HEAD)")
+      if [ $? -ne 0 ]; then
+        echo "Error deploying application version: $result"
+        exit 1
+      fi
         
     - name: Start Bot
       run: |
